services:
    scrape_bot:
        container_name: scrape_bot
        build:
            dockerfile: ./Dockerfile
            context: .
        expose:
            - 8134
            - 8133
            - 8132
        volumes:
            - ./temp:/app/temp
        restart: always
        networks:
            - infra
networks:
    infra:
        external: true
